apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
  - port: 80 # exposição no serviço
    targetPort: 80 # porta de acesso no pod
